### ISSUE TITLE
403 when accessing dogs_vs_cats

### ISSUE THREAD

**Issue by henkmet** [mlverse/torchdatasets#28]
I'm trying to DL the dogs_vs_cats dataset following the tutorial on rstudio (https://blogs.rstudio.com/ai/posts/2021-06-17-luz/) but I'm getting a 403 forbidden. Not sure whether the issue is in torchdatasets or in pins. I do have a kaggle.json in ~/.kaggle/kaggle.json

````Downloading: 120 B     Error in pin_download_one(p, ...) :
  Client error: (403) Forbidden. Failed to download remote file: https://www.kaggle.com/api/v1/competitions/data/download/dogs-vs-cats/train.zip````

**Comment by flsck** [comment]
Hey there,

(403) could be an indication that you have not agreed to the conditions of the associated kaggle competition. 
Cats vs. Dogs is the data from the following: https://www.kaggle.com/competitions/dogs-vs-cats/
If you check out the tab "Data", Kaggle will ask whether or not you agree the ToS of the competition. This is necessary to download the data with your Kaggle token. Upon accepting the conditions, you should be able to download the data with the relevant function (tested this on the 01.0 release).

**Comment by henkmet** [comment]
So silly of me to never think of that. It does indeed download fine after agreeing to ToS. Thanks a lot.
